version: "3"
services:
  db:
    image: "postgres"
    container_name: "demo_postgres"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=public
    ports:
      - "54320:5432"
#    volumes:
#      - ./postgres-data:/var/lib/postgresql/data